In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load dataset
df = pd.read_csv("data_lomba_mentah.csv")

print("data_lomba_mentah.csv:")
display(df.head())

data_lomba_mentah.csv:

,Judul,Jenjang,Biaya Registrasi,Tipe (Online/Offline),Tanggal Pelaksanaan,Penyelenggara,Tema/Kategori,Link Poster
0,Pi-Spektra,SD / Sederajat,Gratis,Online,3 - 16 Mar 2025,SMP Daarut Tauhiid Boarding School Putri,"Musik, Agama, English",https://infolomba.id/images/event/poster/pispe...
1,Medical Veteran Project 2025,Mahasiswa,Rp 80.000,Online & Offline,17 Agu - 6 Sep 2025,BEM FK UPN “Veteran” Jakarta,"Desain, Olahraga, Seni",https://infolomba.id/images/event/poster/medic...
2,Mujahidin Excellent Fest 2026,"SD / Sederajat, SMP / Sederajat",Rp 45.000,Offline,5 - 22 Feb 2026,SMP Mujahidin Surabaya,"Olimpiade, Agama",https://infolomba.id/images/event/poster/mujah...
3,Lomba Mural Tadjimalela,"SMA / Sederajat, Gapyear, Mahasiswa, Umum",Rp 100.000,Offline,1 - 25 Jan 2026,Mural Tadjimalela,"Desain, Seni, ~Lainnya",https://infolomba.id/images/event/poster/lomba...
4,Lomba Video Mengulas Buku!✨📚,"SMP / Sederajat, SMA / Sederajat, Gapyear, Mah...",Gratis,Online,11 Agu - 8 Sep 2025,Yayasan Gelora Insan Mandiri,"~Lainnya, Videografi/Film, Challenge",https://infolomba.id/images/event/poster/lomba...

In [3]:
print("========= ASSESSING df =========")
df.info()
print("\nMissing values di df:\n", df.isna().sum())

========= ASSESSING df =========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Judul                  1512 non-null   object
 1   Jenjang                1509 non-null   object
 2   Biaya Registrasi       1506 non-null   object
 3   Tipe (Online/Offline)  1512 non-null   object
 4   Tanggal Pelaksanaan    1512 non-null   object
 5   Penyelenggara          1507 non-null   object
 6   Tema/Kategori          1506 non-null   object
 7   Link Poster            1512 non-null   object
dtypes: object(8)
memory usage: 94.6+ KB

Missing values di df:
 Judul                    0
Jenjang                  3
Biaya Registrasi         6
Tipe (Online/Offline)    0
Tanggal Pelaksanaan      0
Penyelenggara            5
Tema/Kategori            6
Link Poster              0
dtype: int64

In [4]:
print("\nJumlah duplikasi di df:", df.duplicated().sum())

Jumlah duplikasi di df: 20

In [5]:
print("\nStatistik deskriptif df:\n")
df.describe()

Statistik deskriptif df:

,Judul,Jenjang,Biaya Registrasi,Tipe (Online/Offline),Tanggal Pelaksanaan,Penyelenggara,Tema/Kategori,Link Poster
count,1512,1509,1506,1512,1512,1507,1506,1512
unique,1427,54,206,3,1388,1364,585,1488
top,Drawing Contest,Mahasiswa,Gratis,Online & Offline,14 Apr - 14 Mei 2025,Olimnesia,Bisnis,https://infolomba.id/images/event/poster/sixty...
freq,3,331,280,640,4,7,65,2

In [6]:
df.head(20)

,Judul,Jenjang,Biaya Registrasi,Tipe (Online/Offline),Tanggal Pelaksanaan,Penyelenggara,Tema/Kategori,Link Poster
0,Pi-Spektra,SD / Sederajat,Gratis,Online,3 - 16 Mar 2025,SMP Daarut Tauhiid Boarding School Putri,"Musik, Agama, English",https://infolomba.id/images/event/poster/pispe...
1,Medical Veteran Project 2025,Mahasiswa,Rp 80.000,Online & Offline,17 Agu - 6 Sep 2025,BEM FK UPN “Veteran” Jakarta,"Desain, Olahraga, Seni",https://infolomba.id/images/event/poster/medic...
2,Mujahidin Excellent Fest 2026,"SD / Sederajat, SMP / Sederajat",Rp 45.000,Offline,5 - 22 Feb 2026,SMP Mujahidin Surabaya,"Olimpiade, Agama",https://infolomba.id/images/event/poster/mujah...
3,Lomba Mural Tadjimalela,"SMA / Sederajat, Gapyear, Mahasiswa, Umum",Rp 100.000,Offline,1 - 25 Jan 2026,Mural Tadjimalela,"Desain, Seni, ~Lainnya",https://infolomba.id/images/event/poster/lomba...
4,Lomba Video Mengulas Buku!✨📚,"SMP / Sederajat, SMA / Sederajat, Gapyear, Mah...",Gratis,Online,11 Agu - 8 Sep 2025,Yayasan Gelora Insan Mandiri,"~Lainnya, Videografi/Film, Challenge",https://infolomba.id/images/event/poster/lomba...
5,FusionTech Challenge 2025,SMA / Sederajat,Rp 15.000,Online & Offline,12 - 26 Feb 2025,Universitas Teknologi Yogyakarta,"Desain, IT, Challenge",https://infolomba.id/images/event/poster/fusio...
6,Olimpiade Manajemen UNAIR 2025,SMA / Sederajat,Rp 90.000,Online & Offline,31 Agu - 10 Sep 2025,Manajemen UNAIR,Olimpiade,https://infolomba.id/images/event/poster/olimp...
7,Lomba MC Nasional,"SMA / Sederajat, Gapyear, Mahasiswa, Umum",Rp 35.000,Online,20 Des 2025 - 20 Jan 2026,OSIS BASWARA Al Munawwir IIBS,MC/Protocol,https://infolomba.id/images/event/poster/lomba...
8,ALKAFEST 2025,"SMP / Sederajat, SMA / Sederajat, Gapyear, Mah...",Rp 75.000,Offline,12 Jun - 12 Agu 2025,SMA Al-Azhar Kelapa Gading,"Musik, Olahraga, Seni",https://infolomba.id/images/event/poster/alkaf...
9,Pharmasteria 2025,SMA / Sederajat,Rp 35.000,Online & Offline,26 Apr - 17 Mei 2025,Himafarsi Universitas Gunadarma,"Desain, Videografi/Film, Esai",https://infolomba.id/images/event/poster/pharm...
10,The 8th ISCOMBUS,Mahasiswa,Rp 50.000,Online,3 - 30 Apr 2025,Himpunan Mahasiswa Manajemen FEB UMY,"Bisnis, English",https://infolomba.id/images/event/poster/the-8...
11,"BHK Cup ""Valore""",SMP / Sederajat,Rp 200.000,Offline,19 Mei - 9 Agu 2025,SMA Bunda Hati Kudus Jakarta,"Olahraga, Seni",https://infolomba.id/images/event/poster/bhk-c...
12,Call for Essay 2025,"Mahasiswa, Umum",Gratis,Online,20 Okt - 20 Des 2025,BSO Literatika FH UNESA,"Esai, Hukum",https://infolomba.id/images/event/poster/call-...
13,HIMABI COMPETITIONS 2025,Mahasiswa,Rp 15.000 - Rp 20.000,Online,21 Des 2025 - 1 Jan 2026,HIMABI Universitas Alma Ata,"Desain, Videografi/Film, Poster",https://infolomba.id/images/event/poster/himab...
14,Pekan Kimia,Mahasiswa,Rp 40.000 - Rp 50.000,Online,26 Nov 2024 - 31 Jan 2025,Himdika FKIP Untan,Desain,https://infolomba.id/images/event/poster/pekan...
15,EUFOGHIA 2025,"SD / Sederajat, SMP / Sederajat, SMA / Sederaj...",Rp 15.000,Online & Offline,21 Agu - 15 Sep 2025,SMA Pesantren Unggul Al Bayan Anyer,"Desain, Musik, Olahraga",https://infolomba.id/images/event/poster/eufog...
16,Vacoos6th,SMA / Sederajat,Rp 140.000 - Rp 155.000,Online & Offline,25 Des 2024 - 8 Feb 2025,MPK-OSIS SMA NEGERI 1 CERME,Musik,https://infolomba.id/images/event/poster/vacoo...
17,Olimpiade Manajemen Universitas Airlangga 2025,SMA / Sederajat,Rp 90.000,Online & Offline,23 - 31 Agu 2025,Management UNAIR,Olimpiade,https://infolomba.id/images/event/poster/olimp...
18,Writing Competition 2026: LKTI BEM Universi La...,SMA / Sederajat,Rp 150.000,Online,20 Des 2025 - 20 Jan 2026,Bem Universitas Muhammadiyah Lamongan,Karya Tulis Ilmiah,https://infolomba.id/images/event/poster/writi...
19,Kelas Intensif SNBT 2025 by MauNgajarin,"SMA / Sederajat, Gapyear, Mahasiswa",Rp 19.000 - Rp 45.000,Online,31 Des 2024 - 12 Jan 2025,MauNgajarin,~Lainnya,https://infolomba.id/images/event/poster/kelas...

## DROP DUPLICATE

In [7]:
df = df.drop_duplicates()
print("\nJumlah duplikasi di df:", df.duplicated().sum())

Jumlah duplikasi di df: 0

## HANDLE MISSING VALUE

In [8]:
# Mengisi nilai kosong sesuai dengan logika masing-masing kolom
df['Jenjang'] = df['Jenjang'].fillna('Umum')
df['Penyelenggara'] = df['Penyelenggara'].fillna('Tidak Diketahui')
df['Tema/Kategori'] = df['Tema/Kategori'].fillna('Lainnya')
df['Biaya Registrasi'] = df['Biaya Registrasi'].fillna('0') # Asumsi kosong = gratis

print("Pengecekan missing values setelah imputasi:")
print(df.isnull().sum())

Pengecekan missing values setelah imputasi:
Judul                    0
Jenjang                  0
Biaya Registrasi         0
Tipe (Online/Offline)    0
Tanggal Pelaksanaan      0
Penyelenggara            0
Tema/Kategori            0
Link Poster              0
dtype: int64

## FEATURE ENGINEERING

Memperbaikin kolonm biaya pendaftaran

In [9]:
import re

def proses_biaya_mean(biaya_str):
    biaya_str = str(biaya_str).lower()
    
    # Jika gratis/free/strip, anggap 0
    if 'gratis' in biaya_str or 'free' in biaya_str or biaya_str == '-' or biaya_str == '0':
        return 0.0
        
    # Bersihkan karakter 'rp', titik, dan spasi
    biaya_str = biaya_str.replace('rp', '').replace('.', '').replace(' ', '')
    
    # Jika berupa range harga (ada tanda '-')
    if '-' in biaya_str:
        parts = biaya_str.split('-')
        try:
            biaya_min = int(parts[0])
            biaya_max = int(parts[1])
            # Ambil nilai tengah (mean)
            return (biaya_min + biaya_max) / 2
        except ValueError:
            return 0.0
    else:
        # Jika harga tunggal (tidak ada range)
        try:
            harga = int(re.sub(r'\D', '', biaya_str)) # Ambil digit angkanya
            return float(harga)
        except ValueError:
            return 0.0

# Aplikasikan fungsi ke kolom Biaya Registrasi
df['Biaya_Rata_Rata'] = df['Biaya Registrasi'].apply(proses_biaya_mean)

# Hapus kolom aslinya karena sudah digantikan dengan angka mean
df = df.drop(columns=['Biaya Registrasi'])

# Cek hasil perubahannya
print("Preview perubahan biaya menjadi Mean:")
df[['Judul', 'Biaya_Rata_Rata']].head(10)

Preview perubahan biaya menjadi Mean:

                            Judul  Biaya_Rata_Rata
0                      Pi-Spektra              0.0
1    Medical Veteran Project 2025          80000.0
2   Mujahidin Excellent Fest 2026          45000.0
3         Lomba Mural Tadjimalela         100000.0
4    Lomba Video Mengulas Buku!✨📚              0.0
5       FusionTech Challenge 2025          15000.0
6  Olimpiade Manajemen UNAIR 2025          90000.0
7               Lomba MC Nasional          35000.0
8                   ALKAFEST 2025          75000.0
9               Pharmasteria 2025          35000.0

In [10]:
# Melihat daftar kolom dan tipe datanya
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1492 entries, 0 to 1511
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Judul                  1492 non-null   object
 1   Jenjang                1492 non-null   object
 2   Tipe (Online/Offline)  1492 non-null   object
 3   Tanggal Pelaksanaan    1492 non-null   object
 4   Penyelenggara          1492 non-null   object
 5   Tema/Kategori          1492 non-null   object
 6   Link Poster            1492 non-null   object
 7   Biaya_Rata_Rata        1492 non-null   float64
dtypes: float64(1), object(7)
memory usage: 104.9+ KB

### Mengubah tipe data

judul : string

jenjang : category

tipe : category

tanggal pelaksanaan : date

penyelenggara : string

tema/kategori :

link poster : string

biaya rata2 : int64

In [11]:
df['Jenjang'] = df['Jenjang'].astype('category') # <--- Tambahkan ini
df['Tipe (Online/Offline)'] = df['Tipe (Online/Offline)'].astype('category')

df['Judul'] = df['Judul'].astype('string')
df['Penyelenggara'] = df['Penyelenggara'].astype('string')
df['Link Poster'] = df['Link Poster'].astype('string')

# Ubah rata-rata biaya jadi integer
df['Biaya_Rata_Rata'] = df['Biaya_Rata_Rata'].astype('int64')

print("✅ Tipe data dasar berhasil diubah!")

✅ Tipe data dasar berhasil diubah!

mengubah format tanggal

In [12]:
# CELL 2: Fungsi pemecah menjadi datetime64 murni
import pandas as pd

def parse_tanggal_datetime(tgl_str):
    tgl_str = str(tgl_str).strip()
    
    # Kamus terjemahan ke bahasa Inggris agar Pandas paham format waktunya
    bulan_indo_eng = {
        'Jan': 'Jan', 'Feb': 'Feb', 'Mar': 'Mar', 'Apr': 'Apr', 
        'Mei': 'May', 'Jun': 'Jun', 'Jul': 'Jul', 'Agu': 'Aug', 
        'Sep': 'Sep', 'Okt': 'Oct', 'Nov': 'Nov', 'Des': 'Dec'
    }
    
    # Kalau tidak ada tanda '-', kembalikan nilai Not a Time (NaT)
    if '-' not in tgl_str:
        return pd.Series([pd.NaT, pd.NaT])
        
    try:
        parts = tgl_str.split('-')
        mulai_str = parts[0].strip()
        selesai_str = parts[1].strip()
        
        # Ekstrak tahun
        tahun = selesai_str.split()[-1]
        
        # Skenario 1: Tanggal mulai cuma angka (contoh: "5 - 22 Feb 2026")
        if len(mulai_str.split()) == 1: 
            bulan_selesai = selesai_str.split()[1]
            mulai_str = f"{mulai_str} {bulan_selesai} {tahun}"
            
        # Skenario 2: Tanggal mulai ada bulan, ga ada tahun (contoh: "14 Feb - 10 Apr 2025")
        elif len(mulai_str.split()) == 2:
            mulai_str = f"{mulai_str} {tahun}"
            
        # Terjemahkan ke bahasa Inggris
        for indo, eng in bulan_indo_eng.items():
            # Pakai spasi di sekitar singkatan biar aman replace-nya
            mulai_str = mulai_str.replace(f" {indo} ", f" {eng} ")
            selesai_str = selesai_str.replace(f" {indo} ", f" {eng} ")
            
        # KONVERSI KE DATETIME PANDAS SECARA PAKSA
        tgl_mulai = pd.to_datetime(mulai_str, format='%d %b %Y')
        tgl_selesai = pd.to_datetime(selesai_str, format='%d %b %Y')
        
        return pd.Series([tgl_mulai, tgl_selesai])
        
    except Exception as e:
        return pd.Series([pd.NaT, pd.NaT])

print("✅ Fungsi parse_tanggal_datetime siap digunakan!")

✅ Fungsi parse_tanggal_datetime siap digunakan!

In [13]:
# 1. Jalankan fungsi dan pecah jadi 2 kolom baru
df[['Tanggal_Mulai', 'Tanggal_Selesai']] = df['Tanggal Pelaksanaan'].apply(parse_tanggal_datetime)

# 2. Buang kolom tanggal yang lama
df = df.drop(columns=['Tanggal Pelaksanaan'])

# 3. Cek hasil struktur terbaru
print("Struktur Data Terbaru:")
df.info()

print("\nPreview Kolom Tanggal (Format standar YYYY-MM-DD):")
display(df[['Judul', 'Tanggal_Mulai', 'Tanggal_Selesai']].head(10))

Struktur Data Terbaru:
<class 'pandas.core.frame.DataFrame'>
Index: 1492 entries, 0 to 1511
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Judul                  1492 non-null   string
 1   Jenjang                1492 non-null   category
 2   Tipe (Online/Offline)  1492 non-null   category
 3   Penyelenggara          1492 non-null   string
 4   Tema/Kategori          1492 non-null   object
 5   Link Poster            1492 non-null   string
 6   Biaya_Rata_Rata        1492 non-null   int64
 7   Tanggal_Mulai          1492 non-null   datetime64[ns]
 8   Tanggal_Selesai        1492 non-null   datetime64[ns]
dtypes: category(2), datetime64[ns](2), int64(1), object(1), string(3)
memory usage: 98.8+ KB

Preview Kolom Tanggal (Format standar YYYY-MM-DD):

                            Judul Tanggal_Mulai Tanggal_Selesai
0                      Pi-Spektra    2025-03-03      2025-03-16
1    Medical Veteran Project 2025    2025-08-17      2025-09-06
2   Mujahidin Excellent Fest 2026    2026-02-05      2026-02-22
3         Lomba Mural Tadjimalela    2026-01-01      2026-01-25
4    Lomba Video Mengulas Buku!✨📚    2025-08-11      2025-09-08
5       FusionTech Challenge 2025    2025-02-12      2025-02-26
6  Olimpiade Manajemen UNAIR 2025    2025-08-31      2025-09-10
7               Lomba MC Nasional    2025-12-20      2026-01-20
8                   ALKAFEST 2025    2025-06-12      2025-08-12
9               Pharmasteria 2025    2025-04-26      2025-05-17

In [14]:
# Ubah kembali kedua kolom tanggal menjadi tipe datetime
df['Tanggal_Mulai'] = pd.to_datetime(df['Tanggal_Mulai'])
df['Tanggal_Selesai'] = pd.to_datetime(df['Tanggal_Selesai'])

# Cek tipe datanya sekarang
print(df[['Tanggal_Mulai', 'Tanggal_Selesai']].dtypes)

Tanggal_Mulai      datetime64[ns]
Tanggal_Selesai    datetime64[ns]
dtype: object

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1492 entries, 0 to 1511
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Judul                  1492 non-null   string
 1   Jenjang                1492 non-null   category
 2   Tipe (Online/Offline)  1492 non-null   category
 3   Penyelenggara          1492 non-null   string
 4   Tema/Kategori          1492 non-null   object
 5   Link Poster            1492 non-null   string
 6   Biaya_Rata_Rata        1492 non-null   int64
 7   Tanggal_Mulai          1492 non-null   datetime64[ns]
 8   Tanggal_Selesai        1492 non-null   datetime64[ns]
dtypes: category(2), datetime64[ns](2), int64(1), object(1), string(3)
memory usage: 98.8+ KB

In [16]:
df.to_csv('data_clean.csv', index=False)

### KATEGORI/TEMA MAPPING

ISI-ISI DOMAIN(dari keyword di kolom kategori/tema):

Akademik : 'Esai', 'Olimpiade', 'Karya Tulis Ilmiah', 'Sastra', 'Debat', 'English', 
        'Pidato', 'Akuntansi', 'Media Pembelajaran', 'Beasiswa', 'Artikel', 
        'Hukum', 'Cerdas Cermat', 'Paper', 'Bahasa Asing', 'Try Out', 'Pajak', 
        'Statistika/Data', 'Keuangan', 'Kesehatan'

Seni Kretif : 'Desain', 'Videografi/Film', 'Musik', 'Seni', 'Poster', 'Infografis', 
        'Fotografi', 'Dance/Tari', 'Menggambar/Drawing/Ilustrasi', 'Mewarnai', 
        'Fashion Show', 'Story Telling', 'MC/Protocol', 'Voice Over', 
        'News Anchor/Pembawa Berita', 'Podcast'

Teknologi : 'IT', 'Teknik', 'Robot', 'UI/UX'

Olahraga & E-Sport : 'Olahraga', 'E-sport'

Bisnis : 'Bisnis', 'Seminar', 'Pelatihan', 'Trading', 'Ambassador'

Lainnya : 'Agama', 'Challenge', '~Lainnya', 'Pramuka', 'Rally Games', 
        'Baris Berbaris', 'Giveaway', 'PMR', 'Permainan', 'Lainnya'

In [17]:
df2 = pd.read_csv("data_clean.csv")

print("data_clean.csv:")
display(df2.head())

data_clean.csv:

,Judul,Jenjang,Tipe (Online/Offline),Penyelenggara,Tema/Kategori,Link Poster,Biaya_Rata_Rata,Tanggal_Mulai,Tanggal_Selesai
0,Pi-Spektra,SD / Sederajat,Online,SMP Daarut Tauhiid Boarding School Putri,"Musik, Agama, English",https://infolomba.id/images/event/poster/pispe...,0,2025-03-03,2025-03-16
1,Medical Veteran Project 2025,Mahasiswa,Online & Offline,BEM FK UPN “Veteran” Jakarta,"Desain, Olahraga, Seni",https://infolomba.id/images/event/poster/medic...,80000,2025-08-17,2025-09-06
2,Mujahidin Excellent Fest 2026,"SD / Sederajat, SMP / Sederajat",Offline,SMP Mujahidin Surabaya,"Olimpiade, Agama",https://infolomba.id/images/event/poster/mujah...,45000,2026-02-05,2026-02-22
3,Lomba Mural Tadjimalela,"SMA / Sederajat, Gapyear, Mahasiswa, Umum",Offline,Mural Tadjimalela,"Desain, Seni, ~Lainnya",https://infolomba.id/images/event/poster/lomba...,100000,2026-01-01,2026-01-25
4,Lomba Video Mengulas Buku!✨📚,"SMP / Sederajat, SMA / Sederajat, Gapyear, Mah...",Online,Yayasan Gelora Insan Mandiri,"~Lainnya, Videografi/Film, Challenge",https://infolomba.id/images/event/poster/lomba...,0,2025-08-11,2025-09-08

In [18]:
# CELL 4: Grouping Domain Kategori (Advanced Level)

# 1. Definisi Mapping Kategori Induk (Super Domain)
# Semua 56 kategori di datamu sudah dimasukkan ke kelompok yang relevan
domain_mapping = {
    'Domain_Akademik': [
        'Esai', 'Olimpiade', 'Karya Tulis Ilmiah', 'Sastra', 'Debat', 'English', 
        'Pidato', 'Akuntansi', 'Media Pembelajaran', 'Beasiswa', 'Artikel', 
        'Hukum', 'Cerdas Cermat', 'Paper', 'Bahasa Asing', 'Try Out', 'Pajak', 
        'Statistika/Data', 'Keuangan', 'Kesehatan'
    ],
    'Domain_Seni_Kreatif': [
        'Desain', 'Videografi/Film', 'Musik', 'Seni', 'Poster', 'Infografis', 
        'Fotografi', 'Dance/Tari', 'Menggambar/Drawing/Ilustrasi', 'Mewarnai', 
        'Fashion Show', 'Story Telling', 'MC/Protocol', 'Voice Over', 
        'News Anchor/Pembawa Berita', 'Podcast'
    ],
    'Domain_Teknologi': [
        'IT', 'Teknik', 'Robot', 'UI/UX'
    ],
    'Domain_Olahraga_E-Sport': [
        'Olahraga', 'E-sport'
    ],
    'Domain_Bisnis_Karir': [
        'Bisnis', 'Seminar', 'Pelatihan', 'Trading', 'Ambassador'
    ],
    'Domain_Umum_Lainnya': [
        'Agama', 'Challenge', '~Lainnya', 'Pramuka', 'Rally Games', 
        'Baris Berbaris', 'Giveaway', 'PMR', 'Permainan', 'Lainnya'
    ]
}

# Bikin dictionary lookup agar mesin cepat mencocokkan katanya
# (Contoh: 'UI/UX' -> 'Domain_Teknologi')
lookup_dict = {}
for domain, kats in domain_mapping.items():
    for k in kats:
        lookup_dict[k] = domain

# 2. Fungsi untuk mengubah deretan kategori mentah menjadi Super Domain
def map_to_domain(teks_kategori):
    teks_kategori = str(teks_kategori).replace(', ', ',')
    kategori_list = teks_kategori.split(',')
    
    domain_terpilih = set() # Pakai set agar tidak ada duplikat domain di 1 lomba
    for kat in kategori_list:
        kat = kat.strip()
        if kat in lookup_dict:
            domain_terpilih.add(lookup_dict[kat])
        elif kat: # Kalau misal ada kategori aneh yang terlewat
            domain_terpilih.add('Domain_Umum_Lainnya') 
            
    # Gabungkan kembali pakai koma (contoh: "Domain_Akademik,Domain_Teknologi")
    return ','.join(list(domain_terpilih))

# 3. Aplikasikan ke kolom Tema/Kategori
df2['Super_Kategori'] = df2['Tema/Kategori'].apply(map_to_domain)

# 4. Lakukan Multi-Label Binarization pada Super Kategori
domain_dummies = df2    ['Super_Kategori'].str.get_dummies(sep=',')

# 5. Gabungkan kolom-kolom baru tersebut ke DataFrame utama
df2 = pd.concat([df2, domain_dummies], axis=1)

# 6. Hapus kolom Tema/Kategori dan Super_Kategori karena sudah jadi angka 0 & 1
df2 = df2.drop(columns=['Tema/Kategori', 'Super_Kategori'])

# Cek hasilnya
print("\n✅ Pemetaan Domain Berhasil!")
print("Bentuk data sekarang:", df2.shape)
display(df2.head())

✅ Pemetaan Domain Berhasil!
Bentuk data sekarang: (1492, 14)

,Judul,Jenjang,Tipe (Online/Offline),Penyelenggara,Link Poster,Biaya_Rata_Rata,Tanggal_Mulai,Tanggal_Selesai,Domain_Akademik,Domain_Bisnis_Karir,Domain_Olahraga_E-Sport,Domain_Seni_Kreatif,Domain_Teknologi,Domain_Umum_Lainnya
0,Pi-Spektra,SD / Sederajat,Online,SMP Daarut Tauhiid Boarding School Putri,https://infolomba.id/images/event/poster/pispe...,0,2025-03-03,2025-03-16,1,0,0,1,0,1
1,Medical Veteran Project 2025,Mahasiswa,Online & Offline,BEM FK UPN “Veteran” Jakarta,https://infolomba.id/images/event/poster/medic...,80000,2025-08-17,2025-09-06,0,0,1,1,0,0
2,Mujahidin Excellent Fest 2026,"SD / Sederajat, SMP / Sederajat",Offline,SMP Mujahidin Surabaya,https://infolomba.id/images/event/poster/mujah...,45000,2026-02-05,2026-02-22,1,0,0,0,0,1
3,Lomba Mural Tadjimalela,"SMA / Sederajat, Gapyear, Mahasiswa, Umum",Offline,Mural Tadjimalela,https://infolomba.id/images/event/poster/lomba...,100000,2026-01-01,2026-01-25,0,0,0,1,0,1
4,Lomba Video Mengulas Buku!✨📚,"SMP / Sederajat, SMA / Sederajat, Gapyear, Mah...",Online,Yayasan Gelora Insan Mandiri,https://infolomba.id/images/event/poster/lomba...,0,2025-08-11,2025-09-08,0,0,0,1,0,1

### Memfokuskan kolom jenjang

Jika jenjangnya lebih dari 3 (berarti 4, 5, dst), ubah jadi 'Umum' dan Jika jenjangnya 1, 2, atau 3, ambil elemen yang paling pertama [0]

In [19]:
# Fungsi untuk menyederhanakan kolom Jenjang
def rapihin_jenjang(teks):
    teks = str(teks)
    # Pecah teks berdasarkan koma dan hapus spasi berlebih
    parts = [p.strip() for p in teks.split(',')]
    
    # Jika jenjangnya lebih dari 3 (berarti 4, 5, dst), ubah jadi 'Umum'
    if len(parts) > 3:
        return 'Umum'
    # Jika jenjangnya 1, 2, atau 3, ambil elemen yang paling pertama [0]
    else:
        return parts[0]

# 1. Aplikasikan fungsinya untuk menimpa kolom Jenjang yang lama
df2['Jenjang'] = df2['Jenjang'].apply(rapihin_jenjang)

# 2. Karena isinya sudah sangat rapi dan seragam, kita ubah lagi jadi tipe 'category' 
# (biar hemat memori dan cepat diolah)
df2['Jenjang'] = df2['Jenjang'].astype('category')

# 3. Cek hasil perubahannya
print("Preview Jenjang yang sudah dirapikan:")
display(df2[['Judul', 'Jenjang']].head(10))

# Jangan lupa save ke CSV akhir kalau ini udah tahap paling final ya!
# df2.to_csv('data_clean_final.csv', index=False)

Preview Jenjang yang sudah dirapikan:

                            Judul          Jenjang
0                      Pi-Spektra   SD / Sederajat
1    Medical Veteran Project 2025        Mahasiswa
2   Mujahidin Excellent Fest 2026   SD / Sederajat
3         Lomba Mural Tadjimalela             Umum
4    Lomba Video Mengulas Buku!✨📚             Umum
5       FusionTech Challenge 2025  SMA / Sederajat
6  Olimpiade Manajemen UNAIR 2025  SMA / Sederajat
7               Lomba MC Nasional             Umum
8                   ALKAFEST 2025             Umum
9               Pharmasteria 2025  SMA / Sederajat

#### Encoding yang jenjang

'SD / Sederajat': 1,
    'SMP / Sederajat': 2,
    'SMA / Sederajat': 3,
    'Mahasiswa': 4,
    'Umum': 5

In [20]:
# Membuat urutan hierarki secara manual (Ordinal Encoding)
mapping_jenjang = {
    'SD / Sederajat': 1,
    'SMP / Sederajat': 2,
    'SMA / Sederajat': 3,
    'Mahasiswa': 4,
    'Umum': 5  # Umum ditaruh tertinggi karena cakupannya paling luas
}

# Terapkan Label Encoding ke kolom Jenjang
df2['Jenjang_Encoded'] = df2['Jenjang'].map(mapping_jenjang)

# Lihat hasilnya
display(df2[['Judul', 'Jenjang', 'Jenjang_Encoded']].head(10))

                            Judul          Jenjang  Jenjang_Encoded
0                      Pi-Spektra   SD / Sederajat              1.0
1    Medical Veteran Project 2025        Mahasiswa              4.0
2   Mujahidin Excellent Fest 2026   SD / Sederajat              1.0
3         Lomba Mural Tadjimalela             Umum              5.0
4    Lomba Video Mengulas Buku!✨📚             Umum              5.0
5       FusionTech Challenge 2025  SMA / Sederajat              3.0
6  Olimpiade Manajemen UNAIR 2025  SMA / Sederajat              3.0
7               Lomba MC Nasional             Umum              5.0
8                   ALKAFEST 2025             Umum              5.0
9               Pharmasteria 2025  SMA / Sederajat              3.0

In [21]:
# Ubah kembali kedua kolom tanggal menjadi tipe datetime
df2['Tanggal_Mulai'] = pd.to_datetime(df2['Tanggal_Mulai'])
df2['Tanggal_Selesai'] = pd.to_datetime(df2['Tanggal_Selesai'])

# Cek tipe datanya sekarang
print(df2[['Tanggal_Mulai', 'Tanggal_Selesai']].dtypes)

Tanggal_Mulai      datetime64[ns]
Tanggal_Selesai    datetime64[ns]
dtype: object

### Encoding Tipe(online/offline)

Kalau lombanya "Online" ➡️ Is_Online = 1, Is_Offline = 0

Kalau lombanya "Offline" ➡️ Is_Online = 0, Is_Offline = 1

Kalau lombanya "Online & Offline" ➡️ Is_Online = 1, Is_Offline = 1 (Karena mendukung keduanya!)

In [22]:
# Membuat kolom Is_Online (Kasih nilai 1 jika ada kata 'Online')
df2['Is_Online'] = df2['Tipe (Online/Offline)'].apply(lambda x: 1 if 'Online' in str(x) else 0)

# Membuat kolom Is_Offline (Kasih nilai 1 jika ada kata 'Offline')
df2['Is_Offline'] = df2['Tipe (Online/Offline)'].apply(lambda x: 1 if 'Offline' in str(x) else 0)

# Hapus kolom aslinya karena sudah diwakili oleh 2 kolom angka di atas
df2 = df2.drop(columns=['Tipe (Online/Offline)'])

# Cek hasil perubahannya
print("Preview perubahan Tipe Lomba:")
display(df2[['Judul', 'Is_Online', 'Is_Offline']].head(10))

Preview perubahan Tipe Lomba:

                            Judul  Is_Online  Is_Offline
0                      Pi-Spektra          1           0
1    Medical Veteran Project 2025          1           1
2   Mujahidin Excellent Fest 2026          0           1
3         Lomba Mural Tadjimalela          0           1
4    Lomba Video Mengulas Buku!✨📚          1           0
5       FusionTech Challenge 2025          1           1
6  Olimpiade Manajemen UNAIR 2025          1           1
7               Lomba MC Nasional          1           0
8                   ALKAFEST 2025          0           1
9               Pharmasteria 2025          1           1

In [23]:
df2.to_csv('hasil_feature.csv', index=False)

In [24]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1492 entries, 0 to 1491
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Judul                    1492 non-null   object
 1   Jenjang                  1492 non-null   category
 2   Penyelenggara            1492 non-null   object
 3   Link Poster              1492 non-null   object
 4   Biaya_Rata_Rata          1492 non-null   int64
 5   Tanggal_Mulai            1492 non-null   datetime64[ns]
 6   Tanggal_Selesai          1492 non-null   datetime64[ns]
 7   Domain_Akademik          1492 non-null   int64
 8   Domain_Bisnis_Karir      1492 non-null   int64
 9   Domain_Olahraga_E-Sport  1492 non-null   int64
 10  Domain_Seni_Kreatif      1492 non-null   int64
 11  Domain_Teknologi         1492 non-null   int64
 12  Domain_Umum_Lainnya      1492 non-null   int64
 13  Jenjang_Encoded          1484 non-null   float64
 14  Is_Online                1492 non-null   int64
 15  Is_Offline               1492 non-null   int64
dtypes: category(1), datetime64[ns](2), float64(1), int64(9), object(3)
memory usage: 176.8+ KB

In [26]:
df2.head(20)

,Judul,Jenjang,Penyelenggara,Link Poster,Biaya_Rata_Rata,Tanggal_Mulai,Tanggal_Selesai,Domain_Akademik,Domain_Bisnis_Karir,Domain_Olahraga_E-Sport,Domain_Seni_Kreatif,Domain_Teknologi,Domain_Umum_Lainnya,Jenjang_Encoded,Is_Online,Is_Offline
0,Pi-Spektra,SD / Sederajat,SMP Daarut Tauhiid Boarding School Putri,https://infolomba.id/images/event/poster/pispe...,0,2025-03-03,2025-03-16,1,0,0,1,0,1,1.0,1,0
1,Medical Veteran Project 2025,Mahasiswa,BEM FK UPN “Veteran” Jakarta,https://infolomba.id/images/event/poster/medic...,80000,2025-08-17,2025-09-06,0,0,1,1,0,0,4.0,1,1
2,Mujahidin Excellent Fest 2026,SD / Sederajat,SMP Mujahidin Surabaya,https://infolomba.id/images/event/poster/mujah...,45000,2026-02-05,2026-02-22,1,0,0,0,0,1,1.0,0,1
3,Lomba Mural Tadjimalela,Umum,Mural Tadjimalela,https://infolomba.id/images/event/poster/lomba...,100000,2026-01-01,2026-01-25,0,0,0,1,0,1,5.0,0,1
4,Lomba Video Mengulas Buku!✨📚,Umum,Yayasan Gelora Insan Mandiri,https://infolomba.id/images/event/poster/lomba...,0,2025-08-11,2025-09-08,0,0,0,1,0,1,5.0,1,0
5,FusionTech Challenge 2025,SMA / Sederajat,Universitas Teknologi Yogyakarta,https://infolomba.id/images/event/poster/fusio...,15000,2025-02-12,2025-02-26,0,0,0,1,1,1,3.0,1,1
6,Olimpiade Manajemen UNAIR 2025,SMA / Sederajat,Manajemen UNAIR,https://infolomba.id/images/event/poster/olimp...,90000,2025-08-31,2025-09-10,1,0,0,0,0,0,3.0,1,1
7,Lomba MC Nasional,Umum,OSIS BASWARA Al Munawwir IIBS,https://infolomba.id/images/event/poster/lomba...,35000,2025-12-20,2026-01-20,0,0,0,1,0,0,5.0,1,0
8,ALKAFEST 2025,Umum,SMA Al-Azhar Kelapa Gading,https://infolomba.id/images/event/poster/alkaf...,75000,2025-06-12,2025-08-12,0,0,1,1,0,0,5.0,0,1
9,Pharmasteria 2025,SMA / Sederajat,Himafarsi Universitas Gunadarma,https://infolomba.id/images/event/poster/pharm...,35000,2025-04-26,2025-05-17,1,0,0,1,0,0,3.0,1,1
10,The 8th ISCOMBUS,Mahasiswa,Himpunan Mahasiswa Manajemen FEB UMY,https://infolomba.id/images/event/poster/the-8...,50000,2025-04-03,2025-04-30,1,1,0,0,0,0,4.0,1,0
11,"BHK Cup ""Valore""",SMP / Sederajat,SMA Bunda Hati Kudus Jakarta,https://infolomba.id/images/event/poster/bhk-c...,200000,2025-05-19,2025-08-09,0,0,1,1,0,0,2.0,0,1
12,Call for Essay 2025,Mahasiswa,BSO Literatika FH UNESA,https://infolomba.id/images/event/poster/call-...,0,2025-10-20,2025-12-20,1,0,0,0,0,0,4.0,1,0
13,HIMABI COMPETITIONS 2025,Mahasiswa,HIMABI Universitas Alma Ata,https://infolomba.id/images/event/poster/himab...,17500,2025-12-21,2026-01-01,0,0,0,1,0,0,4.0,1,0
14,Pekan Kimia,Mahasiswa,Himdika FKIP Untan,https://infolomba.id/images/event/poster/pekan...,45000,2024-11-26,2025-01-31,0,0,0,1,0,0,4.0,1,0
15,EUFOGHIA 2025,Umum,SMA Pesantren Unggul Al Bayan Anyer,https://infolomba.id/images/event/poster/eufog...,15000,2025-08-21,2025-09-15,0,0,1,1,0,0,5.0,1,1
16,Vacoos6th,SMA / Sederajat,MPK-OSIS SMA NEGERI 1 CERME,https://infolomba.id/images/event/poster/vacoo...,147500,2024-12-25,2025-02-08,0,0,0,1,0,0,3.0,1,1
17,Olimpiade Manajemen Universitas Airlangga 2025,SMA / Sederajat,Management UNAIR,https://infolomba.id/images/event/poster/olimp...,90000,2025-08-23,2025-08-31,1,0,0,0,0,0,3.0,1,1
18,Writing Competition 2026: LKTI BEM Universi La...,SMA / Sederajat,Bem Universitas Muhammadiyah Lamongan,https://infolomba.id/images/event/poster/writi...,150000,2025-12-20,2026-01-20,1,0,0,0,0,0,3.0,1,0
19,Kelas Intensif SNBT 2025 by MauNgajarin,SMA / Sederajat,MauNgajarin,https://infolomba.id/images/event/poster/kelas...,32000,2024-12-31,2025-01-12,0,0,0,0,0,1,3.0,1,0